valor_1 = input("valor 1= ")
valor_2 = input("valor 2= ")
valor_3 = input("valor 3= ")
valor_4 = input("valor 4= ")
valor_5 = input("valor 5= ")

print(f"{valor_1:->10}")
print(f"{valor_2:->10}")
print(f"{valor_3:->10}")
print(f"{valor_4:->10}")
print(f"{valor_5:->10}")
